name = "Sherlogs"
uuid = "d4954a42-a18b-4f81-bb79-24f1192c93d8"
authors = ["Milan Kloewer"]
version = "0.2.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
StatsBase = "^0.32"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
